### ISSUE TITLE
What is the difference between @poziworld/oauth2orize and oauth2orize npm packages?

### ISSUE THREAD

**Issue by alexbaumgertner** [jaredhanson/oauth2orize-discuss#4]
https://yarnpkg.com/en/package/oauth2orize and
https://yarnpkg.com/en/package/@poziworld/oauth2orize

Almost the same packages (author, repo), but they have different versions.

**Comment by PoziWorld** [comment]
@poziworld/oauth2orize replaced auto-loading of grant & exchanges for packageability to allow the server to be packaged with webpack or similar and to be deployed as a serverless lambda (for example, with ZEIT Now).

Details: 
https://github.com/PoziWorld/oauth2orize/commit/364b9cfc8c68c92670a839e143ac72c25a4a5c1f

**Comment by alexbaumgertner** [comment]
Thank you!
